version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - pay-card-network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
    networks:
      - pay-card-network
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=amazon
    networks:
      - pay-card-network
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pay-card-network
  idempotency-ms:
    depends_on:
      - mongo
      - redis
    build: 
      context: ./idempotency-ms
      target: dev 
    container_name: idempotency
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./idempotency-ms:/usr/share/app
    environment:
      - PORT=3001
      - MONGODB=mongodb://mongo:27017/amazon
      - REDIS=redis://redis:6379
      - HOST_CREATE=http://switch:3002/switch/create
      - HOST_CANCEL=http://switch:3002/switch/cancel
    networks:
      - pay-card-network
  adapter-ms:
    build: 
      context: ./adapter-ms
      target: dev
    restart: always
    container_name: adapter
    ports:
      - "3000:3000"
    volumes:
      - ./adapter-ms:/usr/share/app
    environment:
      - PORT=3000
      - URL_IDEMPOTENCY_CREATED=http://idempotency:3001/idempotency/create
    networks:
      - pay-card-network
  switch-ms:
    depends_on:
      - rabbitmq
    build: 
      context: ./switch-ms
      target: dev
    restart: always
    container_name: switch
    volumes:
      - ./switch-ms:/usr/share/app
    ports:
      - "3002:3002"
    environment:
      - HOST_AMQP=amqp://guest:guest@rabbit:5672
      - QUEUE_NAME=base48
      - PORT=3002
    networks:
      - pay-card-network
  base48:
    depends_on:
      - rabbitmq
    build: 
      context: ./base48
      target: dev
    restart: always
    volumes:
      - ./base48:/usr/share/app
    container_name: base48
    ports:
      - "3003:3003"
    environment:
      - HOST_AMQP=amqp://guest:guest@rabbit:5672
      - QUEUE_RECEIVER_NAME=base48
      - QUEUE_SEND_NAME=payment
      - PORT=3003
    networks:
      - pay-card-network
  consumer-ms:
    depends_on:
      - rabbitmq
    build: 
      context: ./consumer-ms
      target: dev
    volumes:
      - ./consumer-ms:/usr/share/app
    restart: always
    container_name: consumer-ms
    ports:
      - "3004:3004"
    environment:
      - HOST_AMQP=amqp://guest:guest@rabbit:5672
      - REDIS=redis://redis:6379
      - QUEUE_NAME=payment
      - PORT=3004
    networks:
      - pay-card-network
networks:
  pay-card-network:
    driver: bridge